name: Deploy Application

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build container
        run: docker build -f Dockerfile . -t globalyouth:latest

      - name: Restart app
        run: docker compose -f /root/docker-compose.yml up -d --force-recreate globalyouth-app
